version: "3.3"
services:
    hamachi:
        container_name: mcserv_hamachi
        image: "gfjardim/hamachi"
        network_mode: "host"
        privileged: true        
        environment:
            - ACCOUNT=your@email.com
        volumes:
            - /opt/container-data/hamachi:/config:rw
            - /etc/localtime:/etc/localtime:ro

    minecraft_server:
        container_name: mcserv_server
        build: .
        ports:
            - "25565:25565/tcp"
            - "25565:25565/udp"
            - "8000:8000/tcp"
        volumes:
            - /opt/mcserv:/opt/mcserv
            - /sys/fs/cgroup:/sys/fs/cgroup:ro
        tmpfs:
            - /run
            - /tmp